[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefer-offline --no-audit"
  # Ayuda con problemas de dependencias opcionales
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

# Configurar redirects para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
